### ISSUE TITLE
Blurb for SC22 poster

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/alliance-comms#13]
We are back to having an in-person booth at SC22 this year. This year we are showing in the MGHPCC booth along with the other founding institutions.
 
I am updating the content for the printed panel and would like to include a blurb about the MOC Alliance. Would you be able to provide one for me? Or direct me to someone who can? We are including a separate blurb about NERC as well, so you should focus on the MOC Alliance. Do you have a new logo/graphic? Or how would you like that presented?
 
Please let me know if you have any questions about this.  

This is for the BU vs. the MGHPCC representation.

**Comment by gmantica** [comment]
Can you please provide an example of the content and format you are looking for from past years?

Thanks!


Gina Mantica (she/her)

Assistant Director, Marketing & Communications

Boston University Rafik B. Hariri Institute for Computing and Computational Science & Engineering

***@***.******@***.***> | 617-353-7942



Follow us: Twitter<https://twitter.com/BU_Computing> | Instagram<https://www.instagram.com/bu_computing/> | LinkedIn<https://www.linkedin.com/company/hariri-institute-for-computing-boston-university> | YouTube<https://www.youtube.com/channel/UCRNfvPRyjlR_zWltFYnmLrQ?view_as=subscriber>

Don't miss out-Sign up for our Newsletter<https://www.bu.edu/hic/how-to-get-involved/contact-us/>!

________________________________

**Comment by okrieg** [comment]
@msdisme I don't see anything to review here Michael, removing it from my assignment.

**Comment by msdisme** [comment]
Closing as done
