### ISSUE TITLE
One-Pager Review

### ISSUE THREAD

**Issue by kkrudolph** [CCI-MOC/alliance-comms#14]

**Comment by okrieg** [comment]
@msdisme when we assign things like this, can we put in the document in as an attachment

**Comment by kkrudolph** [comment]
Most recent version of the one-pager [https://app.zenhub.com/files/533821647/327fdf90-2567-4a0c-9a63-7117d7f59cc4/download](https://app.zenhub.com/files/533821647/327fdf90-2567-4a0c-9a63-7117d7f59cc4/download)

**Comment by okrieg** [comment]
This looks great to me!!

**Comment by okrieg** [comment]
@msdisme this keeps apearing as assinged to me?

**Comment by msdisme** [comment]
I think this is done @kkrudolph - reopen if I am mistaken.
