### ISSUE TITLE
bug:community form text says profile will be editable, it is not at this point

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/alliance-comms#25]
community form text says profile will be editable, it is not at this point so we should either fix it so it is, or change text to something like "contact X to make changes."

![image.png](https://images.zenhubusercontent.com/62b0bcb4ba912dbb31713c09/99d160aa-92fd-4238-8d92-00125862f0ca)

**Comment by msdisme** [comment]
button gone, but happening elsewhere and waiting on feedback from support team.

**Comment by taramoran** [comment]
ken reaching back out to form Helpdesk
