### ISSUE TITLE
forward looking list of systems seminars for Ken to use on web site

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/alliance-comms#28]
Orran mentioned Ari Trachtenberg has a spreadsheet of these going forward - if possible we should get it to update the site farther in advance.

**Comment by msdisme** [comment]
@kkrudolph can you please put the link to the spreadsheet here so others may use it?  Thanks!

**Comment by kkrudolph** [comment]
@msdisme https://docs.google.com/document/d/1IPtE4UgqGD8eAg04t3wn31NZibB0_j0IGRQNEKypFW4/edit?usp=sharing
