### ISSUE TITLE
on community page  make the default sort bubble the core dev team to the top.   

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/alliance-comms#29]
Which would include Nancy, Tara, Dev team.  

Dev team wants to feel some love.

**Comment by okrieg** [comment]
What do you mean by an MOC Alliance Team?  Isn't everyone in the MOC Alliance team?

**Comment by msdisme** [comment]
A proposal for how to simplify this, keep the larger group, and make the default sort bubble the core dev team to the top.   

Context: Some of the dev team are feeling a bit "less important" than on the old page, which is fair because potentially the way the page works the developers may be below a bunch of interns.

**Comment by okrieg** [comment]
I like that, but what is the definition of developers?  Does this include only the people we fund? Lars?  Ming?  Does this also include the core operations staff from OCT and NERC?   I wouldn't mind something that highlighted the core full time team, but I think that should include NERC operations and folks working full time with us from red hat.  Does that make sense?

**Comment by knikolla** [comment]
I am happy highlighting whoever else we want to highlight and debating the definition of the core team, but I *strongly* don't like being in the Community page far down the bottom, after PhD, alumni and interns.

One thing to keep in mind is that NERC Operations has the NERC Website where they are featured prominently. Same goes for all other initiatives. The core MOC team doesn't.
