### ISSUE TITLE
Leadership and Ops & Admin Pages

### ISSUE THREAD

**Issue by kkrudolph** [CCI-MOC/alliance-comms#3]

**Comment by kkrudolph** [comment]
https://massopen.cloud/leadership-team/

**Comment by msdisme** [comment]
- [ ]

**Comment by kkrudolph** [comment]
https://docs.google.com/document/d/1QYRj_BXSONLg1X-YifzVa9xng9kNlUag0TXwExCNzlQ/edit?usp=sharing

**Comment by kkrudolph** [comment]
@msdisme @okrieg If you all could look over the google doc in the previous comment and assist me with making sure all of the names and titles are correct and creating short descriptions for the operations team that would be great. Thank you!

**Comment by msdisme** [comment]
- [x] @msdisme send mail to karsten to get photo
- [ ] @msdisme send mail to folks on leadership page asking for approval

**Comment by taramoran** [comment]
@kkrudolph feel free to ping Michael when good to send for approval, or you can send it to the leadership team directly whenever you're good

**Comment by msdisme** [comment]
@kkrudolph please remove the email addresses before I send for feedback.  Need to ask/offer option to give a link eg. to linkedin or their contact page.

**Comment by kkrudolph** [comment]
@msdisme Done! I removed the email addresses and links to their home org profile pages.

**Comment by msdisme** [comment]
closing based on note sent november 3 and only positive feedback.
