### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by kkrudolph** [CCI-MOC/alliance-comms#4]

**Comment by kkrudolph** [comment]
https://massopen.cloud/community/

**Comment by kkrudolph** [comment]
@okrieg I have updated the Community page and form with the updates we discussed, could you look over the page and let me know if you have any more updates? Thanks!

**Comment by msdisme** [comment]
@kkrudolph. did you get the feedback you needed on this from Orran?  if so plz remove him from assignees.  I will give feedback shortly as well and will remove myself once done.  I attached a screenshot for Karsten.  
![Karsten-2022-headshot](https://user-images.githubusercontent.com/6126065/194958438-baacdf08-8768-45e0-9e49-539b7a501f9b.jpg)

**Comment by msdisme** [comment]
feedback on page.  i think you got some of this from discussion last week
- what will the process for updating my information be?  eg. I want to put in my info and add a headshot later.
- Will arrangement be alphabetical?
- for other is there a way to have it look at what others have done to help drive common use of names-similar to how tags usually work from a ux perspective

**Comment by okrieg** [comment]
Ken, looked over, now that I am on zenhub, tracking things assigned to me.  I think we were going to change search to filter like linkedin does, and there was a question if we were going to have aditional categories rather than projects, i.e, a filter for projects, a filter for role (PI, marketing, engineering perhaps? ).  Also, question, is the content of the writeup in markdown, so people can put in, for example links to external sites?  Last question/comment, can we put in something describing in the form the update process?  That is, once it is reviewed for first add, people can update it... and how?  I fill in forms very different if I know they are one-shot or repeated.  Am removing myself from being assigned on this, please add me back after you have addressed or commented.  Lets get this out this week if at all possible and sent to engineers and leadership team.

**Comment by kkrudolph** [comment]
@okrieg @msdisme 

Hi Michael and Orran, I have made all of the requested updates to the Community Page and I have answers to your questions!

Updates made:

- I added a new “Role” field to the form. I put in a few default options including PI, Leadership, Engineering, and Marketing & Communications as well as an other field so people can input their role if it does not fall under these options. Let me know if you want me to add any other roles or edit these options.

- I tried my best to mimic the way LinkedIn utilizes filters. There is now a basic search bar at the top as well as a more filters button that opens a sidebar with filters for projects, role, and status. Check out the new search features and let me know what you think and if you have any edits!

Question answers:

- what will the process for updating my information be? eg. I want to put in my info and add a headshot later.
    - Profiles can be updated by the user who initially filled out the form or any site admin, I have put the following instructions at the top of the form: Once submitted you can edit any information on your profile by selecting your profile on the listings page and clicking the "edit profile" button in the top right corner.

- Will arrangement be alphabetical?
    - Currently the default view for the community page will sort the profiles alphabetically by last name. If you would like this to be organized in a different way let me know and I can change it.

- for other is there a way to have it look at what others have done to help drive common use of names-similar to how tags usually work from a ux perspective
    - To help people know what to put when filling out the form, they are able to view any of the other profiles to look at an example. The only written field that isn’t simply selecting options is the involvement in the MOC Alliance description, where I have added the following instructions: In a few sentences please describe how you are involved in or contributed to the MOC Alliance.

- is the content of the writeup in markdown, so people can put in, for example links to external sites?
    - You cannot put links in the written field “Involvement in the MOC Alliance” but there is an optional field “Website” to provide an external link to a personal website or profile on another website.

**Comment by msdisme** [comment]
@kkrudolph for community page - re email field on detail page can we make sure email is not mandatory?  eg. https://massopen.cloud/community/member/bo24q/ shows it, but others may want to route folks to linkedin or other contact methods.

**Comment by kkrudolph** [comment]
@msdisme completed this as well, email is no longer a required field on the Community Form

**Comment by msdisme** [comment]
thought you may have - thanks :-)

**Comment by msdisme** [comment]
Closing as these issues are resolved
