### ISSUE TITLE
MOC Alliance Partners Logos surrounding MOC Alliance

### ISSUE THREAD

**Issue by kkrudolph** [CCI-MOC/alliance-comms#9]

**Comment by kkrudolph** [comment]
![MOC Alliance Structure Graphic Draft 1-12.png](https://images.zenhubusercontent.com/631b41282a423c2eda517165/041ef730-944c-4702-8688-749cc61a9ccf)

**Comment by kkrudolph** [comment]
@okrieg I have been working on developing some MOC Alliance graphics. I saw you used a version of this graphic in the slides at the RFP event and I finished this first draft. Let me know what you think and if you have any edits. Thanks!

**Comment by msdisme** [comment]
@kkrudolph I added okrieg as an assignee so it will show up in his github tasks as well (the @okrieg does it but assigning it makes it more visible.)
 
We will invite him to zenhub probably next week.

**Comment by kkrudolph** [comment]
@msdisme This is the powerpoint file I have been building the editable graphics in. You can copy and paste the whole graphic or parts into any powerpoint! https://bushare-my.sharepoint.com/:p:/g/personal/kkr_bu_edu/EcKJ_GYl3BNDuiMEE0xloacB0oK7E0-DsZhee3IIp5VDyA?e=tPfhhU

**Comment by msdisme** [comment]
@kkrudolph  two thoughts on this- 1. should it include founding partners (RH, 2 Sigma?)  (instinct is no)  2.  But then the RH and BU joint logos do not really make it clear that it is the RH Collaboratory (though it may be all that was approved.   

Newer one appears to be here: https://drive.google.com/drive/folders/1Dwrdq2I15mQ-4YG8DP30vQsqTJ9zS3qC

**Comment by kkrudolph** [comment]
@msdisme This graphic was based on this previous figure from the briefing document: ![Screen Shot 2022-10-20 at 1.07.00 PM.png](https://images.zenhubusercontent.com/631b41282a423c2eda517165/2f0568ed-e776-4da2-be54-9329fd998112) 

My understanding is that this graphic is meant to frame the goals and structure of the MOC Alliance and how our different projects and programs interact, so we would not want to include industry partners like Two Sigma and Red Hat.

I do not believe we have an official Red Hat Collaboratory logo other than the Red Hat logo with BU brick. Gina has told me in the past we have to get approval to do anything with the Red Hat logo. We should discuss and decide if we should make a logo/wordmark for the RHC and get that approved by Red Hat.

Let me know if you want any changes to this graphic including changing the grouping of the projects or additional logos of other projects. I have seen other versions of this graphic that included other logos such as i-scale and the ChRis logo.

For partners I have drafted the following graphic to highlight our various industry and academic partners. I haven't touched this graphic in a bit, Sophia said we are still working out who are official partners and finding their official logos, so some of the logos may be subject to change.![MOC Alliance Materials Partners Draft-18.png](https://images.zenhubusercontent.com/631b41282a423c2eda517165/98a1822c-1792-4361-ba07-0e5973efada5)

**Comment by msdisme** [comment]
Looks great!!  (And I love what you did in the Pitch Deck Master!
